#!/bin/sh

socket_path="/tmp/xwm"
# enumerated endpoints in dwm.c
getclients=0  
selectclient=1  

# retrieve clients list from wm and pipe it to menu
clients=$(echo -e "$getclients" | nc -u "$socket_path")
selected_client=$(echo -e "$clients" | menu)

# extract the position from the selected client string
# assuming the client string format "pos client_name"
selected_pos=$(echo "$selected_client" | cut -d ' ' -f1)

# construct msg to set focus on the selected client and send it to wm
message="$selectclient\n$selected_pos"
echo -e "$message" | nc -u "$socket_path"