#!/bin/bash

SOCKET_PATH="/tmp/xwm"
GetClient=0 # Corresponding to the enumerated endpoint in dwm.c

POS=0 # Client position to query
clients=""
connected=true

# Send the command and client position, save the response, until closed
while : ; do
    if echo "$GetClient \n $POS" | nc.openbsd -U "$SOCKET_PATH"; then
        echo "Socket connected."
        connected=true
        while IFS= read -r c; do
            clients="$clients\n$c"
            echo "Received: $c"
            ((POS++))
        done
    else
        if $connected; then
            echo "Socket closed. Exiting."
        else
            echo "Error: Unable to open socket at $SOCKET_PATH"
        fi
        break
    fi
done

selected_client=$(echo -e "$clients" | sort -u | dmenu "$@")

# Find the position of the selected client
POS=0
client_pos=-1
while IFS= read -r client; do
    if [[ "$client" == "$selected_client" ]]; then
        client_pos=$POS
        break
    fi
    ((POS++))
done <<< "$(echo -e "$clients")"

util_switch.sh "$client_pos" &